import { FileText, Download, CheckCircle, Clock } from "lucide-react";
import { toast } from "sonner";

const reports = [
  {
    title: "GHG Protocol Annual Report — FY 2025",
    framework: "GHG Protocol",
    status: "Ready",
    date: "2026-01-15",
    pages: 42,
  },
  {
    title: "CDP Climate Change Response",
    framework: "CDP",
    status: "Ready",
    date: "2026-02-01",
    pages: 38,
  },
  {
    title: "TCFD Aligned Disclosure",
    framework: "TCFD",
    status: "Ready",
    date: "2026-02-10",
    pages: 26,
  },
  {
    title: "SBTi Progress Report Q4 2025",
    framework: "SBTi",
    status: "Generating",
    date: "2026-03-11",
    pages: null,
  },
  {
    title: "ISO 14064-1 Verification Report",
    framework: "ISO 14064",
    status: "Ready",
    date: "2025-12-20",
    pages: 54,
  },
];

const Reports = () => {
  const handleDownload = (report: typeof reports[0]) => {
    toast.success(`Preparing ${report.title} for download...`);
    
    const htmlContent = `
      <!DOCTYPE html>
      <html>
      <head>
        <title>${report.title}</title>
        <style>
          body { font-family: sans-serif; padding: 40px; color: #333; line-height: 1.6; }
          .header { border-bottom: 2px solid #10b981; padding-bottom: 20px; margin-bottom: 30px; }
          h1 { margin: 0; color: #111; }
          .meta { color: #666; font-size: 0.9em; margin-top: 10px; }
          .section { margin-bottom: 30px; }
          .section-title { font-weight: bold; font-size: 1.2em; margin-bottom: 15px; color: #10b981; }
          table { width: 100%; border-collapse: collapse; margin-top: 10px; }
          th, td { border: 1px solid #ddd; padding: 12px; text-align: left; }
          th { bg-color: #f9fafb; }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>${report.title}</h1>
          <div class="meta">
            Framework: ${report.framework} | Date: ${report.date} | Status: ${report.status}
          </div>
        </div>
        
        <div class="section">
          <div class="section-title">Executive Summary</div>
          <p>This report provides a comprehensive overview of sustainability performance and carbon emissions data for the specified period, aligned with the ${report.framework} framework.</p>
        </div>

        <div class="section">
          <div class="section-title">Emissions Breakdown</div>
          <table>
            <thead>
              <tr>
                <th>Category</th>
                <th>Emissions (tCO2e)</th>
                <th>Trend</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>Scope 1 (Direct)</td>
                <td>1,240.5</td>
                <td>-4.2%</td>
              </tr>
              <tr>
                <td>Scope 2 (Indirect - Energy)</td>
                <td>850.2</td>
                <td>-12.8%</td>
              </tr>
              <tr>
                <td>Scope 3 (Value Chain)</td>
                <td>12,450.0</td>
                <td>+2.1%</td>
              </tr>
            </tbody>
          </table>
        </div>

        <div class="section">
          <div class="section-title">Targets & Progress</div>
          <p>The organization is currently on track to meet its 2030 Net Zero targets, with a significant reduction in Scope 2 emissions following the transition to renewable energy sources.</p>
        </div>

        <div style="margin-top: 50px; font-size: 0.8em; color: #999; text-align: center;">
          Generated by EcoLens Sustainability Platform
        </div>
      </body>
      </html>
    `;

    const blob = new Blob([htmlContent], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${report.title.replace(/\s+/g, '_')}.html`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-6 max-w-4xl">
      <div>
        <h1 className="font-display text-2xl font-bold text-foreground">ESG Compliance Reports</h1>
        <p className="text-sm text-muted-foreground">Downloadable reports aligned to major sustainability frameworks</p>
      </div>

      <div className="grid grid-cols-1 gap-3 md:grid-cols-2">
        <div className="rounded-xl border border-primary/20 bg-primary/5 p-5">
          <p className="text-xs uppercase tracking-wider text-primary font-medium">Reports Generated</p>
          <p className="font-display text-3xl font-bold text-foreground mt-1">14</p>
          <p className="text-xs text-muted-foreground">This fiscal year</p>
        </div>
        <div className="rounded-xl border border-border bg-card p-5 shadow-card">
          <p className="text-xs uppercase tracking-wider text-muted-foreground font-medium">Frameworks Covered</p>
          <p className="font-display text-3xl font-bold text-foreground mt-1">5</p>
          <p className="text-xs text-muted-foreground">GHG, CDP, TCFD, SBTi, ISO</p>
        </div>
      </div>

      <div className="space-y-3">
        {reports.map((report, i) => (
          <div key={i} className="flex items-center gap-4 rounded-xl border border-border bg-card px-6 py-4 shadow-card">
            <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg bg-muted">
              <FileText className="h-5 w-5 text-muted-foreground" />
            </div>
            <div className="flex-1 min-0">
              <p className="font-display text-sm font-semibold text-foreground truncate">{report.title}</p>
              <div className="flex items-center gap-3 mt-1">
                <span className="text-xs text-muted-foreground">{report.framework}</span>
                <span className="text-xs text-muted-foreground">·</span>
                <span className="text-xs text-muted-foreground">{report.date}</span>
                {report.pages && <span className="text-xs text-muted-foreground">· {report.pages} pages</span>}
              </div>
            </div>
            <div className="flex items-center gap-3 shrink-0">
              {report.status === "Ready" ? (
                <>
                  <span className="flex items-center gap-1 text-xs text-primary">
                    <CheckCircle className="h-3.5 w-3.5" /> Ready
                  </span>
                  <button
                    onClick={() => handleDownload(report)}
                    className="flex items-center gap-1.5 rounded-lg border border-border px-3 py-2 text-xs font-medium text-foreground hover:bg-muted transition-colors"
                  >
                    <Download className="h-3.5 w-3.5" /> Download
                  </button>
                </>
              ) : (
                <span className="flex items-center gap-1 text-xs text-destructive">
                  <Clock className="h-3.5 w-3.5 animate-spin" /> Generating...
                </span>
              )}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};

export default Reports;
